name: nlp_env
channels:
  - menpo
  - conda-forge
  - defaults
dependencies:
  - apptools=4.4.0=py35_2
  - asn1crypto=0.24.0=py35_2
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.5=py_1
  - bkcharts=0.2=py35_0
  - bleach=1.5.0=py35_0
  - blinker=1.4=py_1
  - blosc=1.14.4=hfc679d8_0
  - bokeh=0.12.6=py35_0
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2018.10.15=ha4d7672_0
  - cachetools=2.1.0=py_0
  - certifi=2018.8.24=py35_1001
  - cffi=1.11.5=py35h5e8e0c9_1
  - chardet=3.0.4=py35_3
  - configobj=5.0.6=py_0
  - cryptography=2.2.1=py35_0
  - cycler=0.10.0=py35_0
  - dbus=1.13.0=h3a4f0e9_0
  - deap=1.2.2=py35hf8a1672_0
  - decorator=4.1.2=py35_0
  - envisage=4.7.0=py_0
  - expat=2.2.5=hfc679d8_1
  - future=0.16.0=py35_2
  - gettext=0.19.8.1=0
  - glib=2.55.0=h464dc38_2
  - google-api-core=1.1.2=py_0
  - google-auth=1.5.1=py_0
  - google-auth-oauthlib=0.1.0=py35_0
  - google-cloud-bigquery=1.5.0=py_0
  - google-cloud-core=0.28.1=py_0
  - google-resumable-media=0.3.1=py_0
  - googleapis-common-protos=1.5.3=py_1
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=1
  - html5lib=0.9999999=py35_0
  - icu=58.2=hfc679d8_0
  - idna=2.7=py35_2
  - imageio=2.3.0=py_1
  - ipykernel=4.6.1=py35_0
  - ipython=6.1.0=py35_0
  - ipython_genutils=0.2.0=py35_0
  - ipywidgets=6.0.0=py35_0
  - jinja2=2.9.6=py35_0
  - jpeg=9c=h470a237_0
  - jsoncpp=1.8.4=h2d50403_1
  - jsonschema=2.6.0=py35_0
  - jupyter_client=5.1.0=py35_0
  - jupyter_core=4.3.0=py35_0
  - libffi=3.2.1=hfc679d8_4
  - libgfortran=3.0.0=1
  - libiconv=1.15=h470a237_2
  - libprotobuf=3.6.0=hd28b015_0
  - libsodium=1.0.16=0
  - libtiff=4.0.9=he6b73bb_1
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_2
  - lzo=2.10=0
  - markupsafe=1.0=py35_0
  - mistune=0.7.4=py35_0
  - mne=0.16.2=py_0
  - nbformat=4.4.0=py35_0
  - ncurses=5.9=10
  - nibabel=2.3.1=pyh24bf2e0_0
  - notebook=5.0.0=py35_0
  - numexpr=2.6.6=py35_0
  - oauthlib=2.1.0=py_0
  - olefile=0.46=py_0
  - openblas=0.2.19=2
  - openssl=1.0.2l=0
  - pandas=0.23.4=py35hf8a1672_0
  - pandas-gbq=0.6.0=py_0
  - pandocfilters=1.4.1=py35_0
  - path.py=10.3.1=py35_0
  - patsy=0.4.1=py35_0
  - pcre=8.41=h470a237_2
  - pexpect=4.2.1=py35_0
  - pickleshare=0.7.4=py35_0
  - pip=9.0.1=py35_1
  - prompt_toolkit=1.0.15=py35_0
  - protobuf=3.6.0=py35hfc679d8_0
  - psycopg2=2.7.1=py35_0
  - pthread-stubs=0.4=h470a237_1
  - ptyprocess=0.5.2=py35_0
  - pyasn1=0.4.4=py_0
  - pyasn1-modules=0.2.1=py_0
  - pycparser=2.18=py_1
  - pydicom=1.2.0=py_0
  - pyface=6.0.0=py_1
  - pygments=2.2.0=py35_0
  - pyjwt=1.6.4=py_0
  - pyopenssl=18.0.0=py35_0
  - pyparsing=2.2.0=py35_0
  - pysocks=1.6.8=py35_1
  - pysurfer=0.9.0=pyh24bf2e0_0
  - python=3.5.4=2
  - python-dateutil=2.6.1=py35_0
  - pytz=2017.2=py35_0
  - pyyaml=3.12=py35_0
  - requests=2.19.1=py35_1
  - requests-oauthlib=0.8.0=py35_1
  - rsa=3.4.2=py_1
  - seaborn=0.9.0=py_0
  - setuptools=27.2.0=py35_0
  - sip=4.18=py35_0
  - six=1.10.0=py35_0
  - sqlalchemy=1.1.13=py35_0
  - sqlite=3.13.0=0
  - statsmodels=0.9.0=py35_0
  - tbb=2019.1=h2d50403_0
  - terminado=0.6=py35_0
  - testpath=0.3.1=py35_0
  - tk=8.5.19=2
  - tornado=4.5.1=py35_0
  - tpot=0.6.4=py35_0
  - traitlets=4.3.2=py35_0
  - traits=4.6.0=py35h470a237_2
  - traitsui=6.0.0=py_1
  - update_checker=0.16=py_0
  - urllib3=1.23=py35_1
  - wcwidth=0.1.7=py35_0
  - webencodings=0.5=py35_0
  - wheel=0.29.0=py35_0
  - widgetsnbextension=2.0.0=py35_0
  - xlrd=1.1.0=py_2
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xz=5.2.3=0
  - yaml=0.1.6=0
  - zeromq=4.1.5=0
  - zlib=1.2.11=0
  - beautifulsoup4=4.6.3=py35_0
  - binutils_impl_linux-64=2.28.1=had2808c_3
  - binutils_linux-64=7.2.0=had2808c_27
  - biopython=1.72=py35h04863e7_0
  - blas=1.0=openblas
  - cairo=1.12.18=6
  - cymem=1.31.2=py35h6bb024c_0
  - cytoolz=0.9.0.1=py35h14c3975_1
  - dill=0.2.8.2=py35_0
  - entrypoints=0.2.3=py35_0
  - fontconfig=2.11.1=6
  - freetds=1.00.9=0
  - freetype=2.5.5=2
  - futures=3.0.3=py35_0
  - futures-compat=1.0=py3_0
  - gcc_impl_linux-64=7.2.0=habb00fd_3
  - gcc_linux-64=7.2.0=h550dcbe_27
  - gxx_impl_linux-64=7.2.0=hdf63c60_3
  - gxx_linux-64=7.2.0=h550dcbe_27
  - h5py=2.7.0=np111py35_0
  - harfbuzz=0.9.39=1
  - hdf5=1.8.17=2
  - ipython-notebook=4.0.4=py35_0
  - jedi=0.10.2=py35_2
  - joblib=0.12.3=py35_0
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgpuarray=0.7.6=h14c3975_0
  - libopenblas=0.2.20=h9ac9557_7
  - libpng=1.6.27=0
  - libpq=9.5.4=0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mako=1.0.7=py35_0
  - matplotlib=1.5.1=np111py35_0
  - mkl=2017.0.3=0
  - mkl-service=1.1.2=py35_3
  - msgpack-numpy=0.4.3.1=py35_0
  - msgpack-python=0.5.6=py35h6bb024c_1
  - murmurhash=0.28.0=py35he6710b0_0
  - nbconvert=5.2.1=py35_0
  - nltk=3.3.0=py35_0
  - numpy=1.11.3=py35h2aefc1b_9
  - numpy-base=1.11.3=py35h7cdd4dd_9
  - pillow=4.2.1=py35_0
  - pixman=0.32.6=0
  - plac=0.9.6=py35_0
  - preshed=1.0.1=py35he6710b0_0
  - pygpu=0.7.6=py35h3010b51_0
  - pymc3=3.3=py35_0
  - pymssql=2.1.3=py35_0
  - pyqt=4.11.4=py35_4
  - pytables=3.3.0=np111py35_0
  - pyzmq=16.0.2=py35_0
  - qt=4.8.7=3
  - readline=6.2=2
  - regex=2018.07.11=py35h14c3975_0
  - scikit-learn=0.19.1=py35_nomklh26d41a3_0
  - scipy=0.19.1=py35_nomklh614202b_3
  - simplegeneric=0.8.1=py35_1
  - spacy=2.0.12=py35h962f231_0
  - termcolor=1.1.0=py35_1
  - theano=1.0.2=py35h6bb024c_0
  - thinc=6.10.3=py35h962f231_0
  - toolz=0.9.0=py35_0
  - tqdm=4.26.0=py35h28b3542_0
  - ujson=1.35=py35h7b6447c_0
  - wrapt=1.10.11=py35h14c3975_2
  - mayavi=4.5.0=py35_0
  - opencv3=3.2.0=np111py35_0
  - vtk=7.0.0=py35_0
  - pip:
    - en-core-web-md==2.0.0
    - en-core-web-sm==2.0.0
    - kaggle==1.5.0
    - msgpack==0.5.6
    - python-slugify==1.2.6
    - tables==3.3.0
    - unidecode==1.0.22
prefix: /home/nbatanay/.conda/envs/nlp_env

